### ISSUE TITLE
Question regarding Signature and Lingo fingerprint

### ISSUE THREAD

**Issue by Jnelen** [cdk/cdk#1017]
Hi there,

I’m curious about how to generate lingo and signature fingerprints for chemical structures.

For lingo fingerprints, I understand that they are based on hashing substrings of the SMILES representation of a molecule. What is the standard length of the bit vector for lingo fingerprints? Is it 1024 bits in the CDK's implementation? I read somewhere it can be variable so that's why i'm asking to be sure.

For signature fingerprints, I’m more confused. What is the length of the bit vector for signature fingerprints? The fingerprint generator says it is -1, while the bit fingerprint says it is 4294967296. The fingerprint generator gives me a list of hashes and a dictionary of substructures for a molecule. Here is an example of what I get for aspirin:

```
 [-2095689706, -1495087878, -1384810070, -517472525, 82126639, 139156478, 1111206930, 1717385191]
 {[C]([C][O]=[O])=2, [O]([C])=1, [C]([C][C]=[C])=1, [C]([C]=[C][O])=1, [O](=[C])=2, [C]([C])=1, [C]([C]=[C])=4, [O]([C][C])=1}
``` 

Could/Should I just use a fixed length of 1024 bits and map the hashes to bit positions "manually"?

I assume that these two fingerprints are not very popular anymore, but I still want to learn how they work. Any help or further information would be greatly appreciated!

**Comment by johnmay** [comment]
In both these cases I believe by default you generate a sparse/unfolded fingerprint. This essentially is like hashing into all possible 32 bit values (2/4 billion depending on signed/unsigned). Normally it’s much more efficient to represent these as a list of the set values rather than a binary fingerprint.In practise most fingerprints can be treated like this and the small (folded) bitmap version (e.g. 1024) is just the hash values modulo the the size of the bit vector (4096, 2048, 1024, 512) etc- JohnOn 10 Oct 2023, at 22:10, Jochem Nelen ***@***.***> wrote:﻿
Hi there,
I’m curious about how to generate lingo and signature fingerprints for chemical structures.
For lingo fingerprints, I understand that they are based on hashing substrings of the SMILES representation of a molecule. What is the standard length of the bit vector for lingo fingerprints? Is it 1024 bits in the CDK's implementation? I read somewhere it can be variable so that's why i'm asking to be sure.
For signature fingerprints, I’m more confused. What is the length of the bit vector for signature fingerprints? The fingerprint generator says it is -1, while the bit fingerprint says it is 4294967296. The fingerprint generator gives me a list of hashes and a dictionary of substructures for a molecule. Here is an example of what I get for aspirin:
 [-2095689706, -1495087878, -1384810070, -517472525, 82126639, 139156478, 1111206930, 1717385191]
 {[C]([C][O]=[O])=2, [O]([C])=1, [C]([C][C]=[C])=1, [C]([C]=[C][O])=1, [O](=[C])=2, [C]([C])=1, [C]([C]=[C])=4, [O]([C][C])=1}

Could/Should I just use a fixed length of 1024 bits and map the hashes to bit positions "manually"?
I assume that these two fingerprints are not very popular anymore, but I still want to learn how they work. Any help or further information would be greatly appreciated!

**Comment by Jnelen** [comment]
Hi, 

Thanks a lot for your response. I figured it was going to be something like this, but wanted confirmation to be sure!
