### ISSUE TITLE
FragmentUtils protected

### ISSUE THREAD

**Issue by lukasmur13** [cdk/cdk#1021]
Hi,

I need to use the method "splitMolecule" from "org.openscience.cdk.fragment.FragmentUtils". I can't access it because the method is declared protected - is there a special reason for it? If so, how can I use its functionality or what is the alternative?

Thanks

**Comment by johnmay** [comment]
You can extend the class then make it public (by a different name). The other option is delete the bond and use the connectivity checker function to get the individual parts. 
The way that method is written is a little tricky since the atoms/bonds end up in two molecules, hence why it's no public.

On a high level what are you trying to do as there might be another way to do it.

**Comment by lukasmur13** [comment]
I was not aware of the connectivity checker function, that does the job. Thank you!
