### ISSUE TITLE
trouble visualizing this SMILES

### ISSUE THREAD

**Issue by egonw** [cdk/cdk#257]
The following SMILES does not seem to visualize nicely with CDKDepict:

    C1=CC=C(C=C1)C#CC2=CC=CC=C2

See https://www.wikidata.org/wiki/Q902100 and http://cdkdepict-openchem.rhcloud.com/depict/bow/svg?smi=C1=CC=C(C=C1)C#CC2=CC=CC=C2&zoom=2.0&annotate=none

I get:

![image](https://cloud.githubusercontent.com/assets/26721/21523142/a61869da-cd0b-11e6-8c53-e6441ed79192.png)

However, pasting the SMILES in the main CDKDepict page makes it show up fine... so, it seems one of the options...

Also, with CDK 1.5.13 in Bioclipse it does show up properly too:

    ui.open(cdk.fromSMILES("C1=CC=C(C=C1)C#CC2=CC=CC=C2"))

I get:

![image](https://cloud.githubusercontent.com/assets/26721/21523145/b2e3da78-cd0b-11e6-8095-7f00cb6f34f2.png)

**Comment by johnmay** [comment]
The # needs to be escaped in the URL:

http://cdkdepict-openchem.rhcloud.com/depict/bow/svg?smi=C1=CC=C(C=C1)C%23CC2=CC=CC=C2

Otherwise the SMILES is truncated to : C1=CC=C(C=C1)C which is Toluene
(hence the abbreviation).

The JS in http://cdkdepict-openchem.rhcloud.com/depict.html does the
correct escaping:

var smi = encodeURIComponent(smiles);
> // okay to not encode these
> smi = smi.replace(/%3D/g, '=');
> smi = smi.replace(/%5B/g, '[');
> smi = smi.replace(/%5D/g, ']');
> smi = smi.replace(/%40/g, '@');


John

**Comment by egonw** [comment]
Duh... shit, should have realized that... sadly, this kind of encoding is not supported by the Wikidata system... clearly applies to many compounds :(
