### ISSUE TITLE
Different fingerprints for same structure

### ISSUE THREAD

**Issue by flmon** [cdk/cdk#377]
In some cases, for two same structures, we get 2 different fingerprints.

I got this problem with class CircularFingerprinter using CLASS_ECFP4. I didn't check if the problem occurs also with other classes or other fingerprint type.

To see a working example, I enclose a SDF file with two same structures that give two different fingerprints.
[test.sdf.txt](https://github.com/cdk/cdk/files/1378866/test.sdf.txt)

**Comment by johnmay** [comment]
The issue is the ECFP fingerprint is stereo specific and the fingerprint does it's own stereo perception from 2D coordinates. Because one of the molecules is drawn as a mix of perspective projection and wedge/hatch bonds the interpretation can get tricky. 

For example here is ChemAxon's Marvin, notice the CIP label are different:

![image](https://user-images.githubusercontent.com/983232/31506680-09ba5970-af70-11e7-87d6-9a8d1d37d4f7.png)

The CDK molfile reader actually gets the same stereo for both inputs and produces the following InChI's:

```txt
InChI=1S/C17H23NO3/c1-18-13-7-8-14(18)10-15(9-13)21-17(20)16(11-19)12-5-3-2-4-6-12/h2-6,13-16,19H,7-11H2,1H3/t13-,14+,15+,16-/m1/s1
InChI=1S/C17H23NO3/c1-18-13-7-8-14(18)10-15(9-13)21-17(20)16(11-19)12-5-3-2-4-6-12/h2-6,13-16,19H,7-11H2,1H3/t13-,14+,15+,16-/m1/s1
```

It is possible to change the ECFP implementation to use the stereochemistry as provided (rather than do it's own perception) but the author (@aclarkxyz) wanted to keep the implementation as independant as possible (so it could be ported to other systems).

A work around is to clear the bond stereo before calculating the fingerprint.

```java
IteratingSDFReader sdfr = new IteratingSDFReader(new FileReader("/Users/john/Downloads/test.sdf"),
                                                 SilentChemObjectBuilder.getInstance(),
                                                 true);        while (sdfr.hasNext()) {
    IAtomContainer mol = sdfr.next();
    IFingerprinter fpr = new CircularFingerprinter(CircularFingerprinter.CLASS_ECFP4);
    for (IBond bond : mol.bonds())
        bond.setStereo(IBond.Stereo.NONE);
    System.out.println(fpr.getFingerprint(mol));
}
```
Results:
```txt
{14, 19, 61, 88, 95, 117, 127, 131, 133, 145, 152, 166, 206, 265, 325, 346, 420, 444, 486, 507, 511, 523, 535, 549, 575, 625, 646, 685, 726, 761, 771, 862, 918, 941, 947, 963, 967, 999}
{14, 19, 61, 88, 95, 117, 127, 131, 133, 145, 152, 166, 206, 265, 325, 346, 420, 444, 486, 507, 511, 523, 535, 549, 575, 625, 646, 685, 726, 761, 771, 862, 918, 941, 947, 963, 967, 999}
```
