### ISSUE TITLE
attempt to rewrite descriptor code so that they do not clone containers

### ISSUE THREAD

**Issue by egonw** [cdk/cdk#406]

**Comment by johnmay** [comment]
Feature Request != Issue

**Comment by johnmay** [comment]
marked for closure

**Comment by egonw** [comment]
Sorry, did not get around to asking you yet. If not in the tracker, where do you like to see feature requests filed again?

**Comment by johnmay** [comment]
I've activated the projects tab in GitHub but whatever works for you. I've got my own CDK todo list in a paper notebook. The issue is "Issue" makes it seem like there is something wrong, the old sourceforge bug/issue/feature tracker was so crammed with stuff it was hard to work out what actually needed to doing from the whimsical possibilities.

**Comment by johnmay** [comment]
https://github.com/cdk/cdk/projects
