### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by RicardoMBorges** [cdk/cdk#440]
Hello, I’m very interested in this, but quite new in programming and/or chemoinformatics.
I believe We can find in here something that will help me.
So, I have an in-house database with several SMILES structures in a CSV file, together with a lot of other information including activity/toxicity simulated data. Do CDK has capabilities to calculate the structural similarity between those SMILES and run it into Cytoscape for visualization?

Thank you

**Comment by egonw** [comment]
Did you see Chemviz2?

**Comment by egonw** [comment]
Yes, basically it has. You probably want to make a TSV file with on each line two compounds, their SMILES, and the similarity. The latter you can calculate with the CDK, e.g. with a rcdk or Groovy script. I suggest to only keep high similarity combinations, because, of course, you can link any SMILES to any SMILES.
