### ISSUE TITLE
Remove some major isotopes

### ISSUE THREAD

**Issue by johnmay** [cdk/cdk#458]
Here are the current "major" isotopes as defined in CDK, I cleaned this up last year such that when there was no information (e.g. all 0 abundance) then it would not select a major one (e.g. Es used to be defined). Actually other higher mass elements should really not have a major definition. Here is the list, could you indicate your thoughts @schymane?

```
H	1
He	4
Li	7
Be	9
B	11
C	12
N	14
O	16
F	19
Ne	20
Na	23
Mg	24
Al	27
Si	28
P	31
S	32
Cl	35
Ar	40
K	39
Ca	40
Sc	45
Ti	48
V	51
Cr	52
Mn	55
Fe	56
Co	59
Ni	58
Cu	63
Zn	64
Ga	69
Ge	74
As	75
Se	80
Br	79
Kr	84
Rb	85
Sr	88
Y	89
Zr	90
Nb	93
Mo	98
Tc	NONE
Ru	102
Rh	103
Pd	106
Ag	107
Cd	114
In	115
Sn	120
Sb	121
Te	130
I	127
Xe	132
Cs	133
Ba	138
La	139
Ce	140
Pr	141
Nd	142
Pm	NONE
Sm	152
Eu	153
Gd	158
Tb	159
Dy	164
Ho	165
Er	166
Tm	169
Yb	174
Lu	175
Hf	180
Ta	181
W	184
Re	187
Os	192
Ir	193
Pt	195
Au	197
Hg	202
Tl	205
Pb	208
Bi	209
Po	NONE
At	NONE
Rn	NONE
Fr	NONE
Ra	NONE
Ac	NONE
Th	232
Pa	231
U	238
Np	NONE
Pu	NONE
Am	NONE
Cm	NONE
Bk	NONE
Cf	NONE
Es	NONE
Fm	NONE
Md	NONE
No	NONE
Lr	NONE
Rf	NONE
Db	NONE
Sg	NONE
Bh	NONE
Hs	NONE
Mt	NONE
Ds	NONE
Rg	NONE
Cn	NONE
Uut	NONE
Nh	NONE
Fl	NONE
Uup	NONE
Mc	NONE
Lv	NONE
Uus	NONE
Ts	NONE
Uuo	NONE
Og	NONE
```

**Comment by schymane** [comment]
I will get back to you hopefully next week … hope you are enjoying ICCS, wish I could be there!

**Comment by egonw** [comment]
Ping @schymane

**Comment by schymane** [comment]
schymane is clearing backlog and this is one that is hard to do on a small screen and without internet while travelling .. it’s on the radar … thx for the ping. Upgraded higher on the pile :-)

**Comment by schymane** [comment]
I've double checked your entire list with the major isotope selected according to abundance listed here, which is extracted from CRC (http://www.sisweb.com/referenc/source/exactmas.htm). They all match with your list with the exception of Pa, which is not present on their website. According to here (https://en.wikipedia.org/wiki/Protactinium), the value for Pa is 231, which matches your list - so from my side all looks good, including those that you've marked as NONE. If you want the excel traceback let me know. I also think this is the best way to define major isotope rather than the method the InChI specs uses to define a "reference" isotope. Sorry it took so long ... finally had a meeting where I could do this on the side :-)

**Comment by johnmay** [comment]
Thanks for checked these.
