### ISSUE TITLE
IteratingSDFReader silently ignores malformed SDF

### ISSUE THREAD

**Issue by janzyka** [cdk/cdk#479]
I noticed that if one provides malformed SDF (like literal `foo` instead of coordinate) the parser silently ignores the error (it logs the error but this is not good enough). [See the offending line](https://github.com/cdk/cdk/blob/6af1ad94638dc11874fa85006302b92a786f5d7b/storage/ctab/src/main/java/org/openscience/cdk/io/iterator/IteratingSDFReader.java#L262).

For such generic parser functionality throwing an (runtime?) exception would be more appropriate so the developer using the parser can decide what to do with parsing error. In our case we want to let our users know that they sent malformed SDF and not silently ignore the error.

If this is accepted as valid issue I will be glad to contribute with the fix.

**Comment by johnmay** [comment]
The **skip** parameter in the constructor controls this:

"Constructs a new IteratingMDLReader that can read Molecule from a given a InputStream. This constructor allows specification of whether the reader will skip 'null' molecules. If skip is set to false and a broken/corrupted molecule is read the iterating reader will stop at the broken molecule. However if skip is set to true then the reader will keep trying to read more molecules until the end of the file is reached."

http://cdk.github.io/cdk/latest/docs/api/index.html?org/openscience/cdk/io/iterator/IteratingSDFReader.html

I added that because processing a 90 million compound SDF for it to fail near the end for example is very frustrating. It should give a better warning though and even with skip turned off it might not give a decent error message. Throwing an exception would not allow to cary on reading so not really a good option. The lower-level APIs give you more control if you need this, for example this idiom works similarly to the ``BufferedReader`` in java..

```
try (MDLV2000Reader mdlr = new MDLV2000Reader("input.sdf")) {
  IAtomContainer mol;
  while ((mol = mdlr.read(builder.newAtomContainer()) != null) {
   
  }
}
```

**Comment by egonw** [comment]
Consider a text-based SDF editor (yes, sometimes you really wish to look at the raw data)... throwing an exception would totally halt the parsing of the file, and making it impossible to find any follow up errors... instead, using an API that signals fatal errors and warnings, the listening editor can actually show that error to the user.

That's why the design is to have a validation flag (then it really fails on fatal format errors) and a situation where these only cause signals...

See http://chem-bla-ics.blogspot.com/2010/01/validating-mdl-sd-files-and-symyx.html

**Comment by janzyka** [comment]
Right, I overlooked the `skip` flag, sorry for that. Is there a way how to find out that the parses actually discovered a broken molecule? It seems that with the `skip` flag on it goes on with parsing but you cannot tell whether a broken molecule was found on the way or not.

**Comment by janzyka** [comment]
I see what you mean. Give the `ErrorHandler` exists it makes sense now. Sorry for false alarm.

**Comment by egonw** [comment]
No worries!
