### ISSUE TITLE
Substructure search using ShortestPathFingerprinter

### ISSUE THREAD

**Issue by likusta** [cdk/cdk#621]
Hello!
I'm trying to realize substructure search. As I understand, the  ShortestPathFingerprinter is suitable for this. I ran into the following problem. I attach two file(in molecules.zip). when using butane.mol as query, should find ciclopentane.mol.  When i found BitSet for butane i got:
{115, 503, 540, 653, 893}
{115, 503, 542, 653, 893} - for ciclopentane. 
So i cannot find ciclopentane. Is there a way to make it work? 

[molecules.zip](https://github.com/cdk/cdk/files/4229281/molecules.zip)

**Comment by steinbeck** [comment]
Can you post this to the CDK-user mailing list rather than here?

Kind regards, Chris


—
Prof. Dr. Christoph Steinbeck
Analytical Chemistry - Cheminformatics and Chemometrics 
Institute for Inorganic and Analytical Chemistry 
Friedrich-Schiller-University 
Lessingstr. 8, D-07743 Jena, Germany 
Phone Secretariat: +49-3641-948171
Email: christoph.steinbeck@uni-jena.de
http://orcid.org/0000-0001-6966-0814

**Comment by likusta** [comment]
Sure. 
Thank you!
