### ISSUE TITLE
Questions about ECFP fingerprint 

### ISSUE THREAD

**Issue by Flora-Feng0532** [cdk/cdk#625]
I did a little math. I was totally confused ( because of my poor programming/math knowledge)
From `long b = i >= 0 ? i : ((i & 0x7FFFFFFF) | (1L << 31));` , b can be in the range (0, 2^64-1).
Then the number of maximum structure patterns that each bit in IBitFingerprint may refer to:
(2^64-1)/2048 ( Suppose fingerprint length= 2048)
In this case, hashing collision is huge.
If the math and logic were correct, is that possible to use crc8 instead of crc32?
Then b can be restricted in the range(0,2^8-1), the collision can be relieved.

`@Override
    public IBitFingerprint getBitFingerprint(IAtomContainer mol) throws CDKException {
        calculate(mol);
        final BitSet bits = new BitSet(length);
        for (int n = 0; n < fplist.size(); n++) {
            int i = fplist.get(n).hashCode;
            long b = i >= 0 ? i : ((i & 0x7FFFFFFF) | (1L << 31));
            bits.set((int) (b % length));
        }
        return new BitSetFingerprint(bits);
    }
`

**Comment by egonw** [comment]
Well, the ECFP algorithm is quite specific and an (industry) standard, so practically we cannot change it. On the collision rate, I think there is some literature about that, but would have to look it up. For example, see this paper: https://chemrxiv.org/articles/A_Probabilistic_Molecular_Fingerprint_for_Big_Data_Settings/7176350

**Comment by Flora-Feng0532** [comment]
> Well, the ECFP algorithm is quite specific and an (industry) standard, so practically we cannot change it. On the collision rate, I think there is some literature about that, but would have to look it up. For example, see this paper: https://chemrxiv.org/articles/A_Probabilistic_Molecular_Fingerprint_for_Big_Data_Settings/7176350

Thanks

**Comment by johnmay** [comment]
Incorrect @egonw, the algorithm is not an industry standard :-).

>> In this case, hashing collision is huge.
>> If the math and logic were correct, is that possible to use crc8 instead of crc32?
>> Then b can be restricted in the range(0,2^8-1), the collision can be relieved.

Maybe I misunderstand but you can also get the fully unfolded fingerprint so in that case using crc8 would not be good. If you do the tests it turns out collisions really aren't an issue for similarity scoring, in fact in my proprietary code I use a very simple but super quick XORSHIFT PRNG. I can't comment on modelling/QSAR but by view is it's misguided to worry about collisions and if you do then just use the fully unfolded "count fingerprint".

> Using the benchmark described by Briem & Lessel (2000) we can compute the precision for each of the 5 activity classes over different fingerprint sizes. As is shown below the precision of 256-bit fingerprints is still reasonable.

![image](https://user-images.githubusercontent.com/983232/78241794-e4e21080-74d8-11ea-9e1e-6538d0fff6f8.png)
