### ISSUE TITLE
MDLV2000 validator: looking for ideas

### ISSUE THREAD

**Issue by flange-ipb** [cdk/cdk#717]
Hi!
We're using JavaScript-based structure editors/viewers as client components in one of our web projects. The components receive and generate molfile V2000 data. This means we are receiving potentially harmful(*) input data from our users and need to validate the input in the backend. I was wondering if cdk offers some way to determine that a molfile is (syntactically) valid.

Best,
Frank

(*) Harmful for other users, who receive data. I'm thinking about XSS attack vectors. You never know exactly, how the structure editors/viewers parse incoming data ...

**Comment by johnmay** [comment]
You can parse a strict flag to a reader (MDLV2000Reader) but likely not robust enough for this purpose. The MDL readers in chemistry toolkits will generally try to be relaxed since they want to accept as much strange inputs they may get as possible. 

For example MOLfiles have significant whitespace but most will still allow malformed input like this:

```

  Mrv1810 03182118592D          

  5  4  0  0  1  0            999 V2000
    0.8250    1.4289    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2375    0.7145    0.0000 C  0  0  0  0  0  0  0  0  0  0  0  0
    0.8250    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2375   -0.7145    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  3  2  1  0  0  0  0
  3  4  1  0  0  0  0
  3  5  1  0  0  0  0
M  END
```

**Comment by egonw** [comment]
The idea of strict and relaxed in the CDK came up because of the points indicated by John. The relaxed mode would complain about every error (things not conform the specification) but not stop parsing. The strict mode would stop parsing. The thing with non-conformatity is the often the parser starts making assumption that do not follow from the standard. Indeed, the input can be wrong, and attempted to be corrected, giving problems during data analysis (not just XSS risks), because people are not aware of the noise introduced.

We used this approach in Bioclipse, where the editor would highlight data that had a parsiing error.

**Comment by flange-ipb** [comment]
Thanks for pointing me to MDLV2000Reader. [My validator implementation](https://github.com/ipb-halle/MolecularFaces/blob/61e7e5a81fb56860ccf38867fd12e62d112b7859/src/main/java/de/ipb_halle/molecularfaces/validator/MolFileValidator.java#L55) now just reads the file and fails upon any exception.
What I noticed is that a molfile with malformed whitespaces (similar to the one mentioned by @johnmay) [fails to validate in both relaxed and strict mode](https://github.com/ipb-halle/MolecularFaces/blob/61e7e5a81fb56860ccf38867fd12e62d112b7859/src/test/java/de/ipb_halle/molecularfaces/validator/MolFileValidatorTest.java#L85). The editor plugins OpenChemLibJS and MarvinJS happily accept it.

**Comment by johnmay** [comment]
I think it depends where the spaces are - I remember now when I made the parsing faster I decided some things are too broken and unlikely to occur :-). Such inputs can cause ambiguities, in your case all the values are defaults but consider something like this:

```
   -7.2917    1.3245    0.0000 N   0  3  0  0  0  0  0  0  0  0  0  0
```

if i delete the first 0 accidentally the 3 get's read in the wrong position 

```
   -7.2917    1.3245    0.0000 N     3  0  0  0  0  0  0  0  0  0  0
```

What about this, the 3 is in the correct position but there was a 0 missing.

```
   -7.2917    1.3245    0.0000 N      3  0  0  0  0  0  0  0  0  0  0
```

The format was original fortan based and you just couldn't get away with such sloppyness. Here's the doc if you fancy writing an uber strict validator:

http://help.accelrysonline.com/ulm/onelab/1.0/content/ulm_pdfs/direct/reference/ctfileformats2016.pdf
