### ISSUE TITLE
Out of Memory error

### ISSUE THREAD

**Issue by lutzweber** [cdk/cdk#723]
When using CDK 2.2 or 2.3 but not 2.1.1 we get an java.lang.OutOfMemoryError: Java heap space
when parsing the following smiles:
C=1(=N(=C=1)(CC)CC)/N=C(/N1CCC(C2=CC=CC#C2)(CN2C(=NC3=C2C=CC=C3)C)CC1)\NCC

we admit that this is a crazy smiles - it was likely produced by OSRA. 

Lutz Weber

**Comment by johnmay** [comment]
Found the issue will post patch in the morning.

**Comment by johnmay** [comment]
SMILES supports extended cis-trans as follows ``C/C=C=C=C/C.C/C=C=C=C\C``:

![](https://www.simolecule.com/cdkdepict/depict/bow/svg?smi=C%2FC%3DC%3DC%3DC%2FC.C%2FC%3DC%3DC%3DC%5CC&w=-1&h=-1&abbr=on&hdisp=bridgehead&showtitle=false&zoom=1.25&annotate=none&r=0)

The issue was in this input there was a loop of cumulated bonds, the code naively presumed this would never (it's impossible in reality) happened so didn't check for the loop and just went round and round until it ran out of memory.

Fixed now: https://github.com/cdk/cdk/commit/8032dff72ed0c6fd86638fe3c06c65b4f46ab59e

@egonw Sorry did make a branch but accidentally pushed to master instead of PR. Let me know if you want anything changed

**Comment by egonw** [comment]
I'll check the patch :)

**Comment by egonw** [comment]
Looks good to me. Thanks for adding the test.
