### ISSUE TITLE
out of memory when getting weights from molecule consisting of chloridehydrochloride salts

### ISSUE THREAD

**Issue by biotech7** [cdk/cdk#737]
when calculating atmoic weights from a molecule which contains chloridehydrochloride salts, it results in heap space problem.  codes as follow:

```java
        IChemObjectBuilder bldr = SilentChemObjectBuilder.getInstance();
        SmilesParser smipar = new SmilesParser(bldr);
        IAtomContainer mol = smipar.parseSmiles("Cl.O=S(=O)(C1=CC=C(NN)C(=C1)C)C");
        double[] cdkWeights = new double[0];
        try {
            cdkWeights = HuLuIndexTool.getAtomWeights(mol);
        } catch (Exception e) {
            System.out.println(e);
        }
```

errors :

```
         Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.openscience.cdk.graph.invariant.HuLuIndexTool.getAtomWeights(HuLuIndexTool.java:135)
```
   
it mostly likes entering in an endless loop resulting in memory overflow.

**Comment by johnmay** [comment]
As a rule of thumb most algorithms in the CDK-EXTRA modules are bit wonky and not maintained well. Since this index tool uses shortest paths between node any molecule with more than one component will fail (since there is no path between the two components). I don't know enough about the algorithm to but a simple fix would be split the molecule up and process each component on it's own (e.g. ```ConnectivityChecker.partitionIntoMolecules()```). 

It actually doesn't look too bad to fix, I would probably update FloydAPSP with -1 to indicate not connected rather than 999,999. Multiple BFS's is actually more efficient. The problem is would these then still be valid HuLuIndexes. More to the point why did you need HuLuIndexes, why not use InChI numbering for example.

**Comment by egonw** [comment]
@rajarshi, didn't you use the `HuluIndexTool` in the past?

**Comment by biotech7** [comment]
@johnmay thanks for your advice，I'll try it. I use HuLuIndexTool for a specific goal which 
 `InChINumbersTools.getNumbers()` cannot reach , ,mainly due to InChI numbering has its own nomenclature rule while HuLuIndexTool only provides unique labels/weights.

**Comment by johnmay** [comment]
> HuLuIndexTool only provides unique labels/weights.

Hmm not sure they're unique :-)

**Comment by johnmay** [comment]
I've got a patch BTW to handle multiple components, not too bad in the end

**Comment by biotech7** [comment]
cheers! 
on some cases, HuLuIndexTool does'nt generate unique weights for every atom when a molecule has symmetric atoms, e.g toluene.

**Comment by biotech7** [comment]
btw, does CDK has the module of calculating pKa value for small  molecules? trying to search this feature but in vain.

**Comment by johnmay** [comment]
> on some cases, HuLuIndexTool does'nt generate unique weights for every atom when a molecule has symmetric atoms, e.g toluene.

**Comment by egonw** [comment]
> btw, does CDK has the module of calculating pKa value for small molecules? trying to search this feature but in vain.

Maybe time to revisit https://chem-bla-ics.blogspot.com/2008/10/pka-prediction-or-how-to-convert-jcim.html

(but I think the issue can be close, correct?)
