### ISSUE TITLE
cdk-tools is not available via Maven

### ISSUE THREAD

**Issue by Mailaender** [cdk/cdk#872]
Tried fetching CDK via @eclipse-m2e, but I constantly keep 

> java.lang.NoClassDefFoundError: org/openscience/cdk/DynamicFactory$CreationModifier

It seems like cdk-tools is simply missing from Maven Central for some reason, yet it is vital for anything to load at all:
* https://search.maven.org/artifact/org.openscience.cdk/cdk-tools/2.7.1/jar
* https://mvnrepository.com/artifact/org.openscience.cdk/cdk-tools

**Comment by johnmay** [comment]
There is no cdk-tools module? cdk-tool (non-plularal) is a parent pom which aggregates tools https://github.com/cdk/cdk/tree/master/tool but you would not import this via maven.

**Comment by johnmay** [comment]
https://search.maven.org/artifact/org.openscience.cdk/cdk-tool/2.7.1/jar but again importing this via Maven makes no sense - note there is no JAR only a POM.

**Comment by johnmay** [comment]
That is the package not the maven module. Logging tool is in the package "cdk-interfaces". The package has no relation on the maven module because some of these classes were written before maven even existed :-).

I would recommend using "cdk-bundle" module which just pull in everything, it's not too big. Otherwise a good start would be to add "cdk-silent" (preferred over "cdk-data") then how you want to read molecules (e.g. "cdk-smiles", or "cdk-ctab" for CTfile/molfiles).

**Comment by Mailaender** [comment]
Added the bundle and imported every module, still I get
> java.lang.NoClassDefFoundError: org/openscience/cdk/exception/InvalidSmilesException

This is probably because it is an Eclipse `.target` platform and not regular Maven.
