### ISSUE TITLE
NPE in CDKAtomTypeMatcher

### ISSUE THREAD

**Issue by uli-f** [cdk/cdk#920]
I opened PR #919 that adds a `@Disabled` test to `CDKAtomTypeMatcherFilesTest`.

Irrespective of the meaningfulness of the chemical structure of the added file `dativeBond.sdf` the `CDKAtomTypeMatcher` throws a `NPE` with that structure due to `IBond.getOrder` being `null` when calling `QueryAtomContainer.getMaximumBondOrder`.

I don't have a concrete idea what should happen in this case, but throwing an NPE is probably not the best outcome... 🤷🏼

**Comment by johnmay** [comment]
See my comment on that PR, unfortunately it's a case of garbage in garbage out... but a better error is "query bond not allowed here or similar".

Since calling the CDKAtomTypeMatcher is optional (and sometimes wrong[1]) this is a tricky one. 

1. the MOL file readers put the correct Hydrogen count using the MDL/Symyx valence model. Applying the CDK model on top of this can change what was provided.
