### ISSUE TITLE
Question: How to use PubchemFingerprinter?

### ISSUE THREAD

**Issue by Kohulan** [cdk/cdk#983]
The Java doc has a code example which says that the PubchemFingerprinter should be implemented like this:
```java
   Molecule molecule = new Molecule();
   PubchemFingerprinter fprinter = new PubchemFingerprinter();
   BitSet fingerprint = fprinter.getBitFingerprint(molecule);
   fprinter.getSize(); // returns 881
   fingerprint.length(); // returns the highest set bit
```

But below that, I also find a note saying the following statement:
```text
"Note that the fingerprinter assumes that you have detected aromaticity and atom types before evaluating 
the fingerprint. Also, the fingerprinter expects that explicit H's are present"
```

Is this statement relevant or could you update the code example accordingly?

**Comment by johnmay** [comment]
I've update the doc but it works the same as every other fingerprint. I also clarified it is (likely) no longer need to provide aromatized molecules and explicit Hydrogens but further testing would be need to be sure. 

Out of interest, why did you want to use it? There are much better fingerprint methods to use that aren't based on predefined keys.

**Comment by Kohulan** [comment]
> Out of interest, why did you want to use it? There are much better fingerprint methods to use that aren't based on predefined keys.
Thanks a lot for this. We have used different fingerprints implemented in CDK and RDKit to calculate Tanimoto similarity for our OCSR work and found PubChem fingerprints to be the most suitable. In addition, we are evaluating deep learning models using different fingerprints and wanted to ensure that the Pubchemfingerprinter was properly implemented.

**Comment by JonasSchaub** [comment]
Do I see this correctly that SmartsPattern.prepare() is applied to every molecule by the PubChemFingerprinter class before generating the fingerprint, detecting aromaticity using the Daylight model? If this is the case, detecting aromaticity by yourself before passing the molecule to the fingerprinter actually makes no sense because the generated aromaticity flags will be overridden anyway, right?

But is it actually tested that the daylight model is suitable to generate results close to the original PubChem implementation?

And about implicit/explicit hydrogens: Here, I was not really able to find according sections in the code. Does the SmartsPattern class basically take care of this by not discriminating between implicit and explicit hydrogens or by testing for both?

Sorry for dumping all these questions, I'm merely asking out of curiosity and also want to make sure that I use this functionality correctly.

**Comment by johnmay** [comment]
Well for OCSR I think it's dubious you use Tanimoto anyways :-). Alas I know it's common practice so you're no worse than others. Since you had many Tc=1.0 but not exact structure match when you reported the results they are probably stereo or regioisomers for which there are better ways to quantify.

> But is it actually tested that the daylight model is suitable to generate results close to the original PubChem implementation?

Yeah the aromaticity no longer needed, but it would perhaps be reasonable to turn off and let the user do. The implicit hydrogen counts were only added recently, i.e. not in the last release.

Note my comment in the code, PubChem actually use something called ESSSR (triplet short). We might be able to approximate it but the Daylight one is closer to this CACTVS one than the CDK I believe.

**Comment by johnmay** [comment]
Either layers of the InChI or something like this: https://nextmovesoftware.github.io/molhash/introduction.html#regioisomer

You can report how many were:
1) Identical
2) Stereoisomers => got stereo wrong
3) Same element graph => got bond orders wrong
4) Regio isomers => write parts connected wrong
5) Same formula => got bonding wrong

**Comment by OBrink** [comment]
Thanks for the feedback, we will have a look at it!
